apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  type: NodePort
  selector:
    app: helloworld-app
  ports:
    - port: 80
      targetPort: 80 #this is where your app is running
      nodePort: 30000 #this is nodeport to access app in browser
